@echo off
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
python.exe -m pip install --upgrade pip
echo -m pip install --upgrade pip...
call venv\Scripts\activate.bat
echo Installing dependencies...
pip install -r requirements.txt
echo Setup complete!